version: '3'
services:
    mongo-cnf-2:
        container_name: "mongo-cnf-2"
        image: daocloud.io/quantaxis/qamongo_single
        ports:
            - "30102:27017"
        command: mongod --replSet cnf-serv --configsvr --port 27017 --oplogSize 16 --noprealloc --smallfiles
        restart: always

    mongo-cnf-3:
        container_name: "mongo-cnf-3"
        image: daocloud.io/quantaxis/qamongo_single
        ports:
            - "30103:27017"
        command: mongod --replSet cnf-serv --configsvr --port 27017 --oplogSize 16 --noprealloc --smallfiles
        restart: always 

    mongo-cnf-1:
        container_name: "mongo-cnf-1"
        image: daocloud.io/quantaxis/qamongo_single
        ports:
            - "30101:27017"
        command: mongod --replSet cnf-serv --configsvr --port 27017 --oplogSize 16 --noprealloc --smallfiles
        links:
            - mongo-cnf-2:mongo-cnf-2
            - mongo-cnf-3:mongo-cnf-3
        restart: always

    mongo-cnf-setup:
        container_name: "mongo-cnf-setup"
        image: daocloud.io/quantaxis/qamongo_single
        depends_on:
            - "mongo-cnf-1"
            - "mongo-cnf-2"
            - "mongo-cnf-3"
        links:
            - mongo-cnf-1:mongo-cnf-1
            - mongo-cnf-2:mongo-cnf-2
            - mongo-cnf-3:mongo-cnf-3
        volumes:
            - ./scripts:/scripts
        environment: 
            - MONGO1=mongo-cnf-1
            - MONGO2=mongo-cnf-2
            - MONGO3=mongo-cnf-3
            - RS=cnf-serv
            - PORT=27017
        entrypoint: [ "sh","-x","/scripts/setup-cnf.sh" ]
