version: '3'
services:
    mongo-1-2:
        container_name: "mongo-1-2"
        image: daocloud.io/quantaxis/qamongo_single
        ports:
            - "30012:27017"
        volumes:
            - ./configs:/etc/mongo
            - ./data/mongo-1-2:/data/db
        command: mongod --replSet rs1 --shardsvr --port 27017  --oplogSize 16 --noprealloc  --config /etc/mongo/shard-server.conf
        restart: always

    mongo-1-3:
        container_name: "mongo-1-3"
        image: daocloud.io/quantaxis/qamongo_single
        ports:
            - "30013:27017"
        volumes:
            - ./configs:/etc/mongo
            - ./data/mongo-1-3:/data/db
        command: mongod --replSet rs1 --shardsvr --port 27017  --oplogSize 16 --noprealloc  --config /etc/mongo/shard-server.conf
        restart: always 

    mongo-1-1:
        container_name: "mongo-1-1"
        image: daocloud.io/quantaxis/qamongo_single
        ports:
            - "30011:27017"
        volumes:
            - ./configs:/etc/mongo
            - ./data/mongo-1-1:/data/db
        command: mongod --replSet rs1 --shardsvr --port 27017  --oplogSize 16 --noprealloc  --config /etc/mongo/shard-server.conf
        links:
            - mongo-1-2:mongo-1-2
            - mongo-1-3:mongo-1-3
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root

    mongo-rs1-setup:
        container_name: "mongo-rs1-setup"
        image: daocloud.io/quantaxis/qamongo_single
        depends_on:
            - "mongo-1-1"
            - "mongo-1-2"
            - "mongo-1-3"
        links:
            - mongo-1-1:mongo-1-1
            - mongo-1-2:mongo-1-2
            - mongo-1-3:mongo-1-3
        volumes:
            - ./scripts:/scripts
        environment: 
            - MONGO1=mongo-1-1
            - MONGO2=mongo-1-2
            - MONGO3=mongo-1-3
            - RS=rs1
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=root
            - MONGO_INITDB=admin
        entrypoint: [ "sh","-x","/scripts/setup.sh" ]

        
