version: '3'
services:
# sharding 副本集 rs1
    mongo-1-2:
        container_name: "mongo-1-2"
        image: daocloud.io/quantaxis/qamongo_single
        volumes:
            - ./data/mongo-1-2:/data/db
        ports:
            - "30012:27017"
        command: mongod --replSet rs1 --dbpath /data/db --shardsvr --port 27017 --oplogSize 16 --noprealloc
        restart: always

    mongo-1-3:
        container_name: "mongo-1-3"
        image: daocloud.io/quantaxis/qamongo_single
        volumes:
            - ./data/mongo-1-3:/data/db
        ports:
            - "30013:27017"
        command: mongod --replSet rs1 --dbpath /data/db --shardsvr --port 27017 --oplogSize 16 --noprealloc
        restart: always

    mongo-1-1:
        container_name: "mongo-1-1"
        image: daocloud.io/quantaxis/qamongo_single
        volumes:
            - ./data/mongo-1-1:/data/db
        ports:
            - "30011:27017"
        command: mongod --replSet rs1 --dbpath /data/db --shardsvr --port 27017 --oplogSize 16 --noprealloc
        restart: always

# sharding 副本集 rs2
    mongo-2-2:
        container_name: "mongo-2-2"
        image: daocloud.io/quantaxis/qamongo_single
        volumes:
            - ./data/mongo-2-2:/data/db
        ports:
            - "30022:27017"
        command: mongod --replSet rs2 --dbpath /data/db --shardsvr --port 27017 --oplogSize 16 --noprealloc
        restart: always

    mongo-2-3:
        container_name: "mongo-2-3"
        image: daocloud.io/quantaxis/qamongo_single
        volumes:
            - ./data/mongo-2-3:/data/db
        ports:
            - "30023:27017"
        command: mongod --replSet rs2 --dbpath /data/db --shardsvr --port 27017 --oplogSize 16 --noprealloc
        restart: always

    mongo-2-1:
        container_name: "mongo-2-1"
        image: daocloud.io/quantaxis/qamongo_single
        volumes:
            - ./data/mongo-2-1:/data/db
        ports:
            - "30021:27017"
        command: mongod --replSet rs2 --dbpath /data/db --shardsvr --port 27017 --oplogSize 16 --noprealloc
        restart: always

    mongo-rs2-setup:
        container_name: "mongo-rs2-setup"
        image: daocloud.io/quantaxis/qamongo_single
        depends_on:
            - "mongo-2-1"
            - "mongo-2-2"
            - "mongo-2-3"
        volumes:
            - ./scripts:/scripts
        environment:
            - MONGO1=mongo-2-1
            - MONGO2=mongo-2-2
            - MONGO3=mongo-2-3
            - RS=rs2
        entrypoint: ["sh", "-x", "/scripts/wait-for-mongodb.sh", "mongo-2-1", "/scripts/wait-for-mongodb.sh", "mongo-2-2", "/scripts/wait-for-mongodb.sh", "mongo-2-3", "/scripts/setup.sh" ]


    mongo-rs1-setup:
        container_name: "mongo-rs1-setup"
        image: daocloud.io/quantaxis/qamongo_single
        depends_on:
            - "mongo-1-1"
            - "mongo-1-2"
            - "mongo-1-3"
        volumes:
            - ./scripts:/scripts
        environment:
            - MONGO1=mongo-1-1
            - MONGO2=mongo-1-2
            - MONGO3=mongo-1-3
            - RS=rs1
        entrypoint: ["sh", "-x", "/scripts/wait-for-mongodb.sh", "mongo-1-1", "/scripts/wait-for-mongodb.sh", "mongo-1-2", "/scripts/wait-for-mongodb.sh", "mongo-1-3", "/scripts/setup.sh" ]


#config 副本集 cnf-serv
    mongo-cnf-2:
        container_name: "mongo-cnf-2"
        image: daocloud.io/quantaxis/qamongo_single
        volumes:
            - ./data/mongo-cnf-2:/data/db
        ports:
            - "30002:27017"
        command: mongod --replSet cnf-serv --dbpath /data/db --configsvr --port 27017 --oplogSize 16 --noprealloc
        restart: always

    mongo-cnf-3:
        container_name: "mongo-cnf-3"
        image: daocloud.io/quantaxis/qamongo_single
        volumes:
            - ./data/mongo-cnf-3:/data/db
        ports:
            - "30003:27017"
        command: mongod --replSet cnf-serv --dbpath /data/db --configsvr --port 27017 --oplogSize 16 --noprealloc
        restart: always

    mongo-cnf-1:
        container_name: "mongo-cnf-1"
        image: daocloud.io/quantaxis/qamongo_single
        volumes:
            - ./data/mongo-cnf-1:/data/db
        ports:
            - "30001:27017"
        command: mongod --replSet cnf-serv --dbpath /data/db --configsvr --port 27017 --oplogSize 16 --noprealloc
        restart: always

    mongo-cnf-setup:
        container_name: "mongo-cnf-setup"
        image: daocloud.io/quantaxis/qamongo_single
        depends_on:
            - "mongo-cnf-1"
            - "mongo-cnf-2"
            - "mongo-cnf-3"
        volumes:
            - ./scripts:/scripts
        environment:
            - MONGO1=mongo-cnf-1
            - MONGO2=mongo-cnf-2
            - MONGO3=mongo-cnf-3
            - RS=cnf-serv
            - PORT=27017
        entrypoint: ["sh", "-x", "/scripts/wait-for-mongodb.sh", "mongo-cnf-1", "/scripts/wait-for-mongodb.sh", "mongo-cnf-2", "/scripts/wait-for-mongodb.sh", "mongo-cnf-3", "/scripts/setup-cnf.sh" ]

# 创建router
    mongo-router:
        container_name: "mongo-router"
        image: daocloud.io/quantaxis/qamongo_single
        volumes:
            - ./data/mongo-router:/data/db
        ports:
            - "40000:27017"
        depends_on:
            - "mongo-rs1-setup"
            - "mongo-rs2-setup"
            - "mongo-cnf-setup"
        command: mongos --configdb cnf-serv/mongo-cnf-1:27017,mongo-cnf-2:27017,mongo-cnf-3:27017
        restart: always

    mongo-shard-setup:
        container_name: "mongo-shard-setup"
        image: daocloud.io/quantaxis/qamongo_single
        depends_on:
            - "mongo-router"
        volumes:
            - ./scripts:/scripts
        environment:
            - MONGOS=mongo-router
            - MONGO11=mongo-1-1
            - MONGO12=mongo-1-2
            - MONGO13=mongo-1-3
            - MONGO21=mongo-2-1
            - MONGO22=mongo-2-2
            - MONGO23=mongo-2-3
            - RS1=rs1
            - RS2=rs2
            - PORT=27017
            - PORT1=27017
            - PORT2=27017
            - PORT3=27017
        entrypoint: ["sh", "-x", "/scripts/wait-for-mongodb.sh", "mongo-1-1", "/scripts/wait-for-mongodb.sh", "mongo-1-2", "/scripts/wait-for-mongodb.sh", "mongo-1-3", "/scripts/wait-for-mongodb.sh", "mongo-2-1", "/scripts/wait-for-mongodb.sh", "mongo-2-2", "/scripts/wait-for-mongodb.sh", "mongo-2-3", "/scripts/wait-for-mongodb.sh", "mongo-router", "/scripts/init-shard.sh" ]
        restart: on-failure:20
