version: '3'
services:
    mongo-2-2:
        container_name: "mongo-2-2"
        image: daocloud.io/quantaxis/qamongo_single
        ports:
            - "30022:27017"
        volumes:
            - ./configs:/etc/mongo
            - ./data/mongo-2-2:/data/db            
        command: mongod --replSet rs2 --shardsvr --port 27017  --oplogSize 16 --noprealloc --smallfiles --config /etc/mongo/shard-server.conf
        restart: always

    mongo-2-3:
        container_name: "mongo-2-3"
        image: daocloud.io/quantaxis/qamongo_single
        ports:
            - "30023:27017"
        volumes:
            - ./configs:/etc/mongo
            - ./data/mongo-2-3:/data/db            
        command: mongod --replSet rs2 --shardsvr --port 27017  --oplogSize 16 --noprealloc --smallfiles --config /etc/mongo/shard-server.conf
        restart: always 

    mongo-2-1:
        container_name: "mongo-2-1"
        image: daocloud.io/quantaxis/qamongo_single
        ports:
            - "30021:27017"
        volumes:
            - ./configs:/etc/mongo
            - ./data/mongo-2-1:/data/db              
        command: mongod --replSet rs2 --shardsvr --port 27017  --oplogSize 16 --noprealloc --smallfiles --config /etc/mongo/shard-server.conf
        links:
            - mongo-2-2:mongo-2-2
            - mongo-2-3:mongo-2-3
        restart: always

    mongo-rs2-setup:
        container_name: "mongo-rs2-setup"
        image: daocloud.io/quantaxis/qamongo_single
        depends_on:
            - "mongo-2-1"
            - "mongo-2-2"
            - "mongo-2-3"
        links:
            - mongo-2-1:mongo-2-1
            - mongo-2-2:mongo-2-2
            - mongo-2-3:mongo-2-3
        volumes:
            - ./scripts:/scripts
        environment: 
            - MONGO1=mongo-2-1
            - MONGO2=mongo-2-2
            - MONGO3=mongo-2-3
            - RS=rs2
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=root
            - MONGO_INITDB=admin
        entrypoint: ["sh","-x", "/scripts/setup.sh" ]

        
