version: '2'
services:
    mongo-cnf-2:
        container_name: "mongo-cnf-2"
        image: mongo:3.4
        volumes:
            - ./data/mongo-cnf-2:/data/db
        ports:
            - "30002:27017"
        command: mongod --replSet cnf-serv --dbpath /data/db --configsvr --port 27017 --oplogSize 16 --noprealloc --smallfiles
        restart: always

    mongo-cnf-3:
        container_name: "mongo-cnf-3"
        image: mongo:3.4
        volumes:
            - ./data/mongo-cnf-3:/data/db
        ports:
            - "30003:27017"
        command: mongod --replSet cnf-serv --dbpath /data/db --configsvr --port 27017 --oplogSize 16 --noprealloc --smallfiles
        restart: always 

    mongo-cnf-1:
        container_name: "mongo-cnf-1"
        image: mongo:3.4
        volumes:
            - ./data/mongo-cnf-1:/data/db
        ports:
            - "30001:27017"
        command: mongod --replSet cnf-serv --dbpath /data/db --configsvr --port 27017 --oplogSize 16 --noprealloc --smallfiles
        links:
            - mongo-cnf-2:mongo-cnf-2
            - mongo-cnf-3:mongo-cnf-3
        restart: always

    mongo-cnf-setup:
        container_name: "mongo-cnf-setup"
        image: mongo:3.4
        depends_on:
            - "mongo-cnf-1"
            - "mongo-cnf-2"
            - "mongo-cnf-3"
        links:
            - mongo-cnf-1:mongo-cnf-1
            - mongo-cnf-2:mongo-cnf-2
            - mongo-cnf-3:mongo-cnf-3
        volumes:
            - ./scripts:/scripts
        environment: 
            - MONGO1=mongo-cnf-1
            - MONGO2=mongo-cnf-2
            - MONGO3=mongo-cnf-3
            - RS=cnf-serv
            - PORT=27017
        entrypoint: [ "/scripts/setup-cnf.sh" ]
